### ISSUE TITLE
Upgrade to Fable.React 2.0 gives warning

### ISSUE THREAD

**Issue by forki** [fable-elmish/react#13]
WARNING in /home/gitlab-runner/.nuget/packages/fable.elmish.react/1.0.0/fable/common.fs
    /home/gitlab-runner/.nuget/packages/fable.elmish.react/1.0.0/fable/common.fs(34,8): (34,11) warning FSHARP: This construct is deprecated. Use ofType
     @ /home/gitlab-runner/.nuget/packages/fable.elmish.react/1.0.0/fable/react.fs 3:0-37
     @ ./App.fs
     @ ./Client.fsproj

I ssume we need a new fable.elmish.react version as well.
/cc @alfonsogarciacaro @et1975

**Comment by forki** [comment]
and worse:

    ERROR in /home/gitlab-runner/.nuget/packages/fable.elmish.react/1.0.0/fable/common.fs
    /home/gitlab-runner/.nuget/packages/fable.elmish.react/1.0.0/fable/common.fs(16,9): (16,17) error FSHARP: No implementation was given for 'abstract member Component.render : unit -> ReactElement'
     @ /home/gitlab-runner/.nuget/packages/fable.elmish.react/1.0.0/fable/react.fs 3:0-37
     @ ./App.fs
     @ ./Client.fsproj

**Comment by MangelMaxime** [comment]
@forki Fable.Elmish.React version 1.0.1-beta-1 should fix all the warning

We released it as a beta 1-2 months ago. And could probably release it out of beta

**Comment by forki** [comment]
1.0.1-beta-1 seems to work yes. but it should go out of beta now. and it should depend on Fable.React >= 2.0.0

**Comment by et1975** [comment]
Released as 1.0.1

**Comment by forki** [comment]
hugs!

2018-01-23 14:26 GMT+01:00 Eugene Tolmachev <notifications@github.com>:
