### ISSUE TITLE
Redux tools with react native

### ISSUE THREAD

**Issue by forki** [fable-elmish/react#18]
Are we using Redux stores with elmish.ReactNative? I tried to use https://github.com/jhen0409/react-native-debugger but it's redux tools does not show our messages

**Comment by alfonsogarciacaro** [comment]
The debugger is a separate package, have you tried that? Not sure if it's compatible with RN though. https://github.com/fable-elmish/debugger

**Comment by et1975** [comment]
We are not using anything of Redux, however the RemoteDev debugger doesn't target Redux specifically. I have tried the debugger with an elmish app about a year ago and it worked, so unless they changed the protocol it should work: 
![screenshot](https://thoughtspam.files.wordpress.com/2017/01/screen-shot-2017-01-11-at-11-33-13-am.png)

Make sure you follow the instructions for setting it up though, the routing the local server and the client all have to be aligned just right.

**Comment by forki** [comment]
@et1975 yes it worked for me with the html react. Ok will try to dig deeper

**Comment by et1975** [comment]
That's not an HTML you are seeing on that screenshot, that's RN. The debugger used for HTML/React connects to a local plugin (that's the default `withDebugger` behaviour). For RN, you need to connect to a "remote" debugger port using `withDebuggerAt`. Take a look at this (really old) diff: https://github.com/fable-elmish/elmish/commit/c41c8b8f14d229f074c0e1d457cc90c03c91251f#diff-d1938dbf6a518fc41d4714abd63fb7b2

**Comment by et1975** [comment]
@forki are we done here?

**Comment by forki** [comment]
Yeah. Still didn't get it working. But will reopen if needed
