### ISSUE TITLE
Allow elmish mailbox to be stopped

### ISSUE THREAD

**Issue by MangelMaxime** [fable-elmish/react#3]
### Description

At my work, we are working with a fullwidth map controlled by one Elmish application. Then, when I need to display some information in a marker I create a new Elmish program instance attach to a *div with an unique id* generated for this marker.

In order to close the marker I remove the generated div. In order to make that possible and not have errors in the console about react being unable to render the view as the div do not exist anymore I made this custom functions:

```fs
    // Equivalent to Elmish.React.Program.withReact
    let withReactCancelToken placeholderId (program:Elmish.Program<_,_,_,_>) =
        let mutable lastRequest = None
        let cts = new System.Threading.CancellationTokenSource()
        let setState model dispatch =
            match lastRequest with
            | Some r -> window.cancelAnimationFrame r
            | _ -> ()

            let element = document.getElementById(placeholderId)
            if isNull element then
                cts.Cancel()
            else
                lastRequest <- Some (window.requestAnimationFrame (fun _ ->
                    Fable.Import.ReactDom.render(
                        Elmish.React.Common.lazyView2With (fun x y -> obj.ReferenceEquals(x,y)) program.view model dispatch,
                        element
                    )))

        { program with setState = setState }, cts

    // Equivalent to Elmish.Program.run
    let runWithAutoCancel (arg: 'arg) ((program: Program<'arg, 'model, 'msg, 'view>), (cts : System.Threading.CancellationTokenSource)) =
        let (model,cmd) = program.init arg
        let inbox = MailboxProcessor.Start(fun (mb:MailboxProcessor<'msg>) ->
            let rec loop (state:'model) =
                async {
                    let! msg = mb.Receive()
                    try
                        let (model',cmd') = program.update msg state
                        program.setState model' mb.Post
                        cmd' |> List.iter (fun sub -> sub mb.Post)
                        return! loop model'
                    with ex ->
                        program.onError ("Unable to process a message:", ex)
                        return! loop state
                }
            loop model
        , cts.Token)
        program.setState model inbox.Post
        program.subscribe model
        @ cmd |> List.iter (fun sub -> sub inbox.Post)
```

This function, add the support for a `CancellationTokenSource` in order to stop the mailbox when the *div element* is not found in the DOM.

@et1975 Should, we include the change I made by default into `Program.withReact` and `Program.run` ?
Should we support both Elmish application without and with cancel support ?

**Comment by et1975** [comment]
This is cool and thank you for sharing, however I don't think running multiple program instances is mainstream enough (or something I'd recommend, although I don't have a specific reason at the moment) to include in the core libraries. I think we need a few more cases to generalize supervisor behaviour, but as you noticed, creating a custom dispatch loop is so simple I'd suggest going with that whenever fine control like this is required.

**Comment by MangelMaxime** [comment]
Yes, my case is probably a special one. 
I agree that users should avoid to run several instance in the same page (I needed it only because, I am using a full map application which is not common). But at least they have now some tracks of how to do it. Was also the goal to share this code :)

I let you either close this issue or mark it with a label if you want.

**Comment by et1975** [comment]
Closing, and hoping people can find it if needed.
