### ISSUE TITLE
elmish-react lazyView... shortcut functions

### ISSUE THREAD

**Issue by michaelsg** [fable-elmish/react#4]
I have a question about elmish-react. Specifically, lazyView, lazyView2, ... .
```fsharp
    let lazyView (view:'model->ReactElement) =
        lazyViewWith (=) view
```
That code will use the structural equality if available on the model, yes?
I feel like reference equality should be the default for these shortcut functions.

I haven't seen these shortcut functions used yet in any of the examples.
The one place where I saw lazyView2With used specifically to protect parts of the UI from unnecessary VDOM regeneration, reference equality was used and that make's perfect sense to me: the model (or any sub model) can only be changed by creating a new instance.

Congrats on your conference!

**Comment by et1975** [comment]
`(=)` implementation shortcuts into reference equality first. The assumption that if the references are equal then the objects are equal falls apart if one was to use a mutable model, so the option is there if you want to do that, but it certainly can't be the default.

**Comment by michaelsg** [comment]
mutable models in elmish? Sounds like trouble. Easy enough to make my own helper functions.
Thanks for the info.
