### ISSUE TITLE
Emit commands from componentDidMount

### ISSUE THREAD

**Issue by forki** [fable-elmish/react#44]
I'd like to get notified when componentDidMount does happen in react native. This is needed to react to deep links into my app.

https://github.com/elmish/react/blob/v3.x/src/react-native.fs#L25

Any ideas how to do it? @MangelMaxime @alfonsogarciacaro @et1975

**Comment by MangelMaxime** [comment]
Create your own `FunctionnalComponent` or any "Stateful component" and pass the `dispatch` via the props. Then in the `componentDidMount` hook/member call `this.props.dispatch ...`.

It will not be the topmost component but can be the second one, I don't think this is a problem.

**Comment by forki** [comment]
any link to a FunctionnalComponent sample in fable?!

**Comment by MangelMaxime** [comment]
You can find the announcement and doc [here](https://fable.io/blog/Announcing-Fable-React-5.html)

**Comment by MangelMaxime** [comment]
You can also see an example of how to deal with disposable event [here](https://github.com/MangelMaxime/fulma-demo/blob/inbox/src/Pages/Inbox.EmailMeta.fs#L186).

**Comment by forki** [comment]
```fs
    type Props = { onComponentDidMount : unit -> unit }

    type MyView(props) =
        inherit Component<Props, obj>(props)

        override __.componentDidMount() =
            props.onComponentDidMount()

        override __.render() = view[][]

    ....
    
    ofType<MyView,_,_> { onComponentDidMount = (fun () -> dispatch Mounted)} []
```

that actually seems to work but I'm not sure what to do with the render method. I want it to be invisible

**Comment by MangelMaxime** [comment]
Instead of `view[][]` use `nothing` if you want to output "nothing" on your view.

**Comment by forki** [comment]
hugs!
