### ISSUE TITLE
Documentation not aligned with API

### ISSUE THREAD

**Issue by marcellourbani** [fable-elmish/react#48]
### Description

I followed the instructions in the [sample code](https://elmish.github.io/react/browser.html), they don't compile

Either the docs need to be updated or semantic versioning has been broken

### Repro code

```F#
module R = Fable.React
```
I created a [sample repo](https://github.com/marcellourbani/fable_react_doc_issue_sample)

### Expected and actual results

Should compile

### Related information 

* elmish version: 3.0.6
* fable-compiler version: 2.4.15
* fable-core version: 3.1.5
* Operating system: Linux (arch)

**Comment by MangelMaxime** [comment]
In a previous version of Fable.React we reworked the API structure.

In general, I think people use `open Fable.React` because it will `AutoOpen` some of the modules etc. but you will not have the prefixed API style.

If you prefer the prefixed API style you can do `module R = Fable.React.Standard`

@et1975 We need to decide which API we prefer to show in Elmis docs

**Comment by marcellourbani** [comment]
@MangelMaxime 
I don't have any preference, I'm a total beginner with a 2 day F# course and a few hours mocking around.

I do have a strong opinion a "getting started" article should work OOTB.

![image](https://user-images.githubusercontent.com/2453277/84886571-86b2db80-b08c-11ea-80e1-482e6df523cb.png)

PS: for the record, `module R = Fable.React.Standard` works for the div but not the str. Looks like it's in Fable.React.Helpers, with a second prefix attached to that does compile

Pushed that to newfix, which does compile and run (completed the other branch too, just in case)

**Comment by MangelMaxime** [comment]
True, then we should just avoid the alias style because now the API is split between several modules. It is hidden when using `open Fable.React` because they are marked with `[<AutoOpen>]`

**Comment by et1975** [comment]
@marcellourbani Thanks for pointing it out!
I agree with @MangelMaxime , and switching to `open Fable.React` should work for new and old React DSL, so there's no downside.
if you want to open a PR for this, please make it to v3.x branch and include just the affected documentation script, nothing else.

Would be great to have the samples updated like [this](https://github.com/elmish/sample-react-navigation/commit/141b16d12b28ff386c4107d90f2051d7287309de) as well, if you're up to it.
