### ISSUE TITLE
Add sample code of a React component to the doc page

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-elmish/react#7]
I've sent a [PR to the React docs](https://github.com/reactjs/reactjs.org/pull/297) with a link [to the elmish-react document](https://fable-elmish.github.io/react/). Not sure yet if it will be accepted, but if it is, there will be probably more people visiting the page so it will be nice to have a very visible sample of a simple component so they can get a quick grip of F# syntax, as in the [ReasonReact](https://reasonml.github.io/reason-react/) web.

**Comment by et1975** [comment]
Hmm, would it not provide apples-to-apples comparison if you link to "plain" Fable sample first, then let the newcomers "graduate" to TEA from there? 
In terms of the sample, the [docs' SPA page](https://fable-elmish.github.io/react/browser.html) is kinda there... no?

**Comment by alfonsogarciacaro** [comment]
Ah, true! I should have linked that, the PR is already merged 😅 

It's not a big issue, I just received several comments of people who like to see a piece of code the first thing in the web, I need to update Fable's website too.
